apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: productservice-rs
  labels:
    app: productservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      name: productservice
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: vgottemukkal/product-service
          imagePullPolicy: IfNotPresent
      restartPolicy: Always